

services:
  db:
    image: postgres:14-alpine
    env_file:
      - .env
  web:
    build: .
    command: python main.py
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db